mode     : selfcontained
framework: dinky
github:
  user: vistat
  repo: supstat

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

url:
  lib: ../libraries
  assets: ../assets

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify



